package ar.com.gire.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bandera implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Character name;

	public Bandera() {
	}

	public java.lang.Character getName() {
		return this.name;
	}

	public void setName(java.lang.Character name) {
		this.name = name;
	}

	public Bandera(java.lang.Character name) {
		this.name = name;
	}

}