package ar.com.gire._0d_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Banco implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Character name;

	public Banco() {
	}

	public java.lang.Character getName() {
		return this.name;
	}

	public void setName(java.lang.Character name) {
		this.name = name;
	}

	public Banco(java.lang.Character name) {
		this.name = name;
	}

}